### ISSUE TITLE
casting with channels doesnt use 100mb

### ISSUE THREAD

**Issue by sreny1** [lJuanGB/TFCCasting#3]
i connected a casting channel with a mold table + ingot mold to a cruciable and casting doesnt use up 100mb.
it uses 97mb most of the time

**Comment by lJuanGB** [comment]
@sreny1 Could you confirm if this is still happening in the latest update? Thanks!

**Comment by sreny1** [comment]
@lJuanGB this does in fact not happen in latest version to me
properly uses the correct amount every time :)
